extends: standard
rules:
  comma-dangle:
    - error
    -
      arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: only-multiline
  object-curly-spacing:
    - error
    - never
  space-before-function-paren:
    - error
    -
      anonymous: always
      named: never
      asyncArrow: always
